name: API report

on: [push, pull_request]

jobs:
  report:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - name: Install
      run: npm i
    - name: Build
      run: npm run build
    - name: API report
      run: npm run api-prod
