# https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

name: Merge upstream branches
on:
  schedule:
    - cron:  '0 4 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      
      - name: Merge upstream
        run: gh repo sync
